# Generated by Django 5.2.12 on 2026-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('nashr_yili', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
